DROP DATABASE IF EXISTS`gestibank`;
CREATE DATABASE IF NOT EXISTS `gestibank` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `gestibank`;
DROP TABLE IF EXISTS `admin`;
CREATE TABLE IF NOT EXISTS `admin` (  `ID` varchar(10) NOT NULL,  `NOM` varchar(30) DEFAULT NULL,  `PRENOM` varchar(20) DEFAULT NULL,  `TYPE_USER` enum('ADMIN','AGENT','CLIENT') DEFAULT NULL,  `mail` int(11) DEFAULT NULL,  PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO `admin` (`ID`, `NOM`, `PRENOM`, `TYPE_USER`, `mail`) VALUES ('0sd01', NULL, NULL, NULL, NULL),('1', NULL, NULL, NULL, NULL);
DROP TABLE IF EXISTS `agent`;
CREATE TABLE IF NOT EXISTS `agent` (  `ID` varchar(10) NOT NULL,  `NOM` varchar(30) DEFAULT NULL,  `PRENOM` varchar(20) DEFAULT NULL,  `TYPE_USER` enum('ADMIN','AGENT','CLIENT') DEFAULT NULL,  `MAIL` varchar(50) DEFAULT NULL,  `TEL` varchar(15) DEFAULT NULL,  `DEBUT_CONTRAT` date DEFAULT NULL,  PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `agent` (`ID`, `NOM`, `PRENOM`, `TYPE_USER`, `MAIL`, `TEL`, `DEBUT_CONTRAT`) VALUES ('j', 'h', 'h', 'ADMIN', 'h', 'h', '2019-09-05');
DROP TABLE IF EXISTS `client`;
CREATE TABLE IF NOT EXISTS `client` (  `ID` varchar(10) NOT NULL,  `NOM` varchar(30) DEFAULT NULL,  `PRENOM` varchar(20) DEFAULT NULL,  `TYPE_USER` enum('ADMIN','AGENT','CLIENT') DEFAULT NULL,  `MAIL` varchar(50) DEFAULT NULL,  `TEL` varchar(15) DEFAULT NULL,  `ADRESSE` varchar(100) DEFAULT NULL,  `JUSTIFICATIF` varchar(30) DEFAULT NULL,  `id_agent` varchar(10) DEFAULT NULL,  PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `client` (`ID`, `NOM`, `PRENOM`, `TYPE_USER`, `MAIL`, `TEL`, `ADRESSE`, `JUSTIFICATIF`, `id_agent`) VALUES ('0029', 'nom_client9', 'prenom_client_09', 'CLIENT', 'client009@gestibank.com', '3792806645', 'adresse', 'None', NULL);
DROP TABLE IF EXISTS `compte`;
CREATE TABLE IF NOT EXISTS `compte` (  `id_compte` varchar(20) NOT NULL,  `id_client` varchar(10) NOT NULL,  `type_compte` enum('COURANT','DECOUVERT','INTERET') NOT NULL,  `rib` varchar(24) NOT NULL,  `solde` float NOT NULL,  `date_creation` date NOT NULL,  PRIMARY KEY (`id_compte`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `compte` (`id_compte`, `id_client`, `type_compte`, `rib`, `solde`, `date_creation`) VALUES ('9744535341', '0020', 'COURANT', '3054368512', 0, '2019-09-05');
DROP TABLE IF EXISTS `demande_creacompte`;
CREATE TABLE IF NOT EXISTS `demande_creacompte` (  `ID` varchar(10) NOT NULL,  `NOM` varchar(30) NOT NULL,  `PRENOM` varchar(20) NOT NULL,  `MAIL` varchar(50) NOT NULL,  `TEL` varchar(15) NOT NULL,  `ADRESSE` varchar(100) NOT NULL,  `JUSTIFICATIF` varchar(30) NOT NULL,  `affect` varchar(15) DEFAULT NULL,  `valide` int(11) DEFAULT NULL,  PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `demande_creacompte` (`ID`, `NOM`, `PRENOM`, `MAIL`, `TEL`, `ADRESSE`, `JUSTIFICATIF`, `affect`, `valide`) VALUES ('1009', 'nom9', 'prenom_9', 'guest009@gestibank.com', '3180386407', 'adresse', 'None', NULL, NULL);
DROP TABLE IF EXISTS `login`;
CREATE TABLE IF NOT EXISTS `login` (  `ID` varchar(10) NOT NULL,  `Password` varchar(50) NOT NULL,  `TYPE_USER` enum('ADMIN','AGENT','CLIENT') NOT NULL,  PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `login` (`ID`, `Password`, `TYPE_USER`) VALUES ('0010', '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29', 'CLIENT'),('0020', '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29', 'AGENT');
